apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-clustercnfdt11-tag-workers
  namespace: cnfdt11
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-clustercnfdt11-tag-worker-cnfdt11
        spec:
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Node
                metadata:
                  labels:
                    node-role.kubernetes.io/worker-cnf: ""
                    ptp/slave: ""
                  name: cnfdt11.lab.eng.tlv2.redhat.com
          severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-clustercnfdt11-tag-workers
placementRef:
  name: cluster-cnfdt11
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-clustercnfdt11-tag-workers
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-cnfdt11
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchLabels:
      name: cnfdt11
